# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: deploy

on:
  push:
    branches:
      - main

concurrency: deployments

jobs:
  deploy:
    if: github.repository_owner == 'motato22'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY_STAGING }}
          dep: deploy --branch=main staging
